config/routes.rb
UserRegistration::Application.routes.draw do
  resources :users
  resources :sessions, only: [:create, :destroy]

  get "/home" => "static_pages#home"
  get "/secret" => "static_pages#secret"

  get "/signup" => "users#new", as: :signup

  get '/signin' => 'sessions#new', as: :signin
  get '/signout'  => 'sessions#destroy', as: :signout

  root 'static_pages#home'

  

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, presence: true
  has_secure_password

  def email=(value)
    value = value.strip.downcase
    write_attribute :email, value
  end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :current_user?

  private
    def current_user
      @user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def current_user?
      current_user.present?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email].downcase)
    if user && user.authenticate(params[:password])
      # save the current user in the session 
      flash[:notice] = "You have been signed in"
      session[:user_id] = user.id
      redirect_to root_url
    else
      flash.now[:alert] = "Incorrect email/password combination."
      render 'new'
    end
  end

  def destroy
    if session[:user_id].present?
      session[:user_id] = nil
      flash[:alert] = "You have been signed out!"
    end
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user, only: :secret

  def home
  end

  def secret
  end

  private
    def authenticate_user
      unless current_user?
        flash[:alert] = "Please signin to access this page"
        redirect_to signin_path
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Thanks for signing up!"
      session[:user_id] = @user.id
      # signin user?
      redirect_to home_url
    else
      flash[:alert] = "Could not signup."
      render 'new'
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email,
                                    :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UserRegistration</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_user? %>
  <div>Welcome, <%= current_user.name %><div>
  <div><%= link_to "Signout", signout_path %></div>
<% else %>
  <div>
    <%= link_to "Signup", signup_path %> |
    <%= link_to "Signin", signin_path %>
  </div>
<% end %>


<%= notice %>
<%= alert %>
<br>
<%= yield %>

</body>
</html>

app/views/static_pages/home.html.erb
<h1>This is my super awesome home page</h1>
<h2>Everyone will <%= link_to "signup", signup_path %> for sure</h2>

app/views/static_pages/secret.html.erb
<h1>This is the most secretest page in the world!</h1>

app/views/users/index.html.erb
<h1>All Users:</h1>
<% if @users %>
  <table border="1">
    <tr>
      <th>Name</th>
      <th>Email</th>
    </tr>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
    </tr>
  <% end %>
  </table>
<% end %>

app/views/users/new.html.erb
<h1>Signup:</h1>

<% @user.errors.full_messages.each do |msg| %>
  <div class="error">
    <%= msg %>
  </div>
<% end %>

<%= form_for @user do |f| %>
  <div>
    <%= f.label :name %></br>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :email %></br>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :password %></br>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %></br>
    <%= f.password_field :password_confirmation %>
  </div>
  <%= f.submit "Signup" %>
<% end %>